#!/bin/sh
### BEGIN INIT INFO
# Provides:          download
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop download server
### END INIT INFO

APPLICATION_ENV=${APPLICATION_ENV:="development"}
case "$1" in
    'stop')
        echo -n "Stoping..."
	pkill -f SMP
	echo -n "Success !"
	;;
    'restart' | 'start')
	if [ $i='start' ];
	then
	    echo -n 'Starting...'
	else
	    echo -n "Restarting..."
	fi
	pkill -f SMP
	nohup /usr/bin/php /var/daemon/SMProtocol/SMProtocol.php > /var/log/SMProtocol.log 2>&1 &
	echo -n "Success !"
	;;
esac
